FROM ruby:2.3.3
MAINTAINER dtk <support.dtk.com>
RUN gem install aws-sdk -v 3.0.1 --no-ri --no-rdoc
RUN gem install rest-client --no-ri --no-rdoc
RUN gem install google-protobuf -v 3.3.0 --no-ri --no-rdoc
RUN gem install grpc -v 1.4.5 --no-ri --no-rdoc
